hdf5-1.8.11.

diff --git a/release_docs/INSTALL_parallel b/release_docs/INSTALL_parallel
--- a/release_docs/INSTALL_parallel
+++ b/release_docs/INSTALL_parallel
@@ -17,12 +17,14 @@ of running the parallel test suites.
 
 1.1. Requirements
 -----------------
-PHDF5 requires an MPI compiler with MPI-IO support and a parallel file system.
-If you don't know yet, you should first consult with your system support staff
-of information how to compile an MPI program, how to run an MPI application,
-and how to access the parallel file system.  There are sample MPI-IO C and
-Fortran programs in the appendix section of "Sample programs".  You can use
-them to run simple tests of your MPI compilers and the parallel file system.
+PHDF5 requires an MPI compiler with MPI-IO support and a POSIX compliant
+(Ref. 1) parallel file system.  If you don't know yet, you should first consult
+with your system support staff of information how to compile an MPI program,
+how to run an MPI application, and how to access the parallel file system.
+There are sample MPI-IO C and Fortran programs in the appendix section of
+"Sample programs".  You can use them to run simple tests of your MPI compilers
+and the parallel file system. Also, the t_posix_compliant test in testpar
+verifies if the file system is POSIX compliant.
 
 
 1.2. Further Help
@@ -106,83 +108,73 @@ This allows for >2GB sized files on Linux systems and is only available with
 Linux kernels 2.4 and greater.
 
 
-2.4. Red Storm (Cray XT3) (for v1.8 and later)
+2.4. Hopper (Cray XE6) (for v1.8 and later)
 -------------------------
-Both serial and parallel HDF5 are supported in Red Storm.
 
-2.4.1 Building serial HDF5 for Red Storm
-------------------------------------------
-The following steps are for building the serial HDF5 for the Red Storm
-compute nodes.  They would probably work for other Cray XT3 systems but have
+2.4.1 Building HDF5 for Hopper
+------------------------------------------ 
+The following steps are for building HDF5 for the Hopper compute
+nodes.  They would probably work for other Cray XE6 systems but have
 not been verified.
 
-# Assume you already have a copy of HDF5 source code in directory `hdf5' and
-# want to install the binary in directory `/project/hdf5/hdf5'.
+Obtain a copy from the HDF ftp server:
+http://www.hdfgroup.org/ftp/HDF5/current/src/
+(link might change, so always double check the HDF group website).
 
-$ cd hdf5
-$ bin/yodconfigure configure
-$ env RUNSERIAL="yod -sz 1" \
-    CC=cc FC=ftn CXX=CC \
-    ./configure --prefix=/project/hdf5/hdf5
-$ make
-$ make check
+$ wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-x.x.x.tar.gz
 
-# if all is well, install the binary.
+unpack the tarball
+
+$ cd hdf5-x.x.x/
+$ CC=cc FC=ftn ./configure \
+--prefix=/project/hdf5/hdf5 --enable-parallel --enable-fortran \
+--disable-shared --disable-production 
+$ make 
+
+Run make check. make check should be run on the compute nodes, not the
+front end nodes.  So using a PBS batch script, allocate 4 or more
+cores. Always consult with the machine's website on how to create PBS
+scripts and allocate nodes for your job. For Hopper, all the
+information can be found on:
+http://www.nersc.gov/systems/hopper-cray-xe6/
+
+save the PBS script into your HDF5 build directory. The PBS script
+should contain (besides the PBS node allocation requests)the
+following:
+
+--------------------------------------------------------------
+cd $PBS_O_WORKDIR
+
+##set RUNSERIAL and RUNPARALLEL like this in the PBS script:
+export RUNPARALLEL="aprun -n 6"
+export RUNSERIAL="aprun -n 1"
+
+##execute make check:
+make check
+--------------------------------------------------------------
+
+Once the job runs and all is well, install the binary:
 $ make install
 
-2.4.2 Building parallel HDF5 for Red Storm
-------------------------------------------
-The following steps are for building the Parallel HDF5 for the Red Storm
-compute nodes.  They would probably work for other Cray XT3 systems but have
-not been verified.
-
-# Assume you already have a copy of HDF5 source code in directory `hdf5' and
-# want to install the binary in directory `/project/hdf5/phdf5'.  You also
-# have done the proper setup to have mpicc and mpif90 as the compiler commands.
-
-$ cd hdf5
-$ bin/yodconfigure configure
-$ env RUNSERIAL="yod -sz 1" RUNPARALLEL="yod -sz 3" \
-    CC=cc FC=ftn \
-    ./configure --enable-parallel --prefix=/project/hdf5/phdf5
-$ make
-$ make check
-
-# if all is well, install the binary.
-$ make install
-
-2.4.3 Red Storm known problems
+2.4.2 Hopper known issues
 ------------------------------
-For Red Storm, a Cray XT3 system, the yod command sometimes gives the
-message,  "yod allocation delayed for node recovery".  This interferes with
-test suites that do not expect seeing this message.  To bypass this problem,
-I launch the executables with a command shell script called "myyod" which
-consists of the following lines.  (You should set $RUNSERIAL and $RUNPARALLEL
-to use myyod instead of yod.)
-==== myyod =======
-#!/bin/sh
-# sleep 2 seconds to allow time for the node recovery else it pops the
-# message,
-#   yod allocation delayed for node recovery
-sleep 2
-yod $*
-==== end of myyod =======
+Sometimes when building the library with make, you might get this problem:
 
-For Red Storm, a Cray XT3 system, the tools/h5ls/testh5ls.sh will fail on
-the test "Testing h5ls -w80 -r -g tgroup.h5" fails.  This test is
-expected to fail and exit with a non-zero code but the yod command does
-not propagate the exit code of the executables. Yod always returns 0 if it
-can launch the executable.  The test suite shell expects a non-zero for
-this particular test, therefore it concludes the test has failed when it
-receives 0 from yod.  To bypass this problem for now, change the following
-lines in the tools/h5ls/testh5ls.sh.
-======== Original =========
-# The following combination of arguments is expected to return an error message
-# and return value 1
-TOOLTEST tgroup-1.ls 1 -w80 -r -g tgroup.h5
-======== Skip the test =========
-echo SKIP TOOLTEST tgroup-1.ls 1 -w80 -r -g tgroup.h5
-======== end of bypass ========
+LD_LIBRARY_PATH="$LD_LIBRARY_PATH`echo | \
+sed -e 's/-L/:/g' -e 's/
+//g'`" \
+./H5make_libsettings > H5lib_settings.c
+|| \
+(test $HDF5_Make_Ignore && echo "*** Error ignored")
+|| \
+(rm -f H5lib_settings.c ; exit 1)
+/bin/sh: line 4: 9644 Segmentation fault
+LD_LIBRARY_PATH="$LD_LIBRARY_PATH`echo | sed -e 's/-L/:/g' -e 's/
+//g'`" ./H5make_libsettings > H5lib_settings.c
+
+If that happens, you are probable running with make -j <x>. In that
+case, you need to cleanup everything and start again as detailed above
+but use serial make (do not use -j <x>).
 
 
 3. Detail explanation
@@ -272,6 +264,20 @@ if the tests should use directory /PFS/user/me, do
 
 (In some batch job system, you many need to hardset HDF5_PARAPREFIX in the
 shell initial files like .profile, .cshrc, etc.)
+
+
+Reference
+---------
+1. POSIX Compliant. A good explanation is by Donald Lewin,
+    After a write() to a regular file has successfully returned, any
+    successful read() from each byte position on the file that was modified
+    by that write() will return the date that was written by the write(). A
+    subsequent write() to the same byte will overwrite the file data. If a
+    read() of a file data can be proven by any means [e.g., MPI_Barrier()]
+    to occur after a write() of that data, it must reflect that write(),
+    even if the calls are made by a different process.
+	Lewin, D. (1994). "POSIX Programmer's Guide (pg. 513-4)". O'Reilly
+	& Associates.
 
 
 Appendix A. Sample programs
