hdf5-1.6.6

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -1,5 +1,6 @@
 #!/bin/sh
 #
+# Copyright by The HDF Group.
 # Copyright by the Board of Trustees of the University of Illinois.
 # All rights reserved.
 #
@@ -9,8 +10,8 @@
 # of the source code distribution tree; Copyright.html can be found at the
 # root level of an installed copy of the electronic HDF5 document set and
 # is linked from the top-level documents page.  It can also be found at
-# http://hdf.ncsa.uiuc.edu/HDF5/doc/Copyright.html.  If you do not have
-# access to either file, you may request a copy from hdfhelp@ncsa.uiuc.edu.
+# http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have
+# access to either file, you may request a copy from help@hdfgroup.org.
 #
 
 # Make a release of hdf5.  The command-line switches are:
@@ -99,6 +100,13 @@ EOF
 
 }
 
+# This command must be run at the top level of the hdf5 source directory.
+# Verify this requirement.
+if [ ! \( -f configure -a -f bin/release \) ]; then
+    echo "$0 must be run at the top level of the hdf5 source directory"
+    exit 1
+fi
+
 # Defaults
 DEST=releases
 VERS=`perl bin/h5vers`
@@ -108,6 +116,7 @@ verbose=yes
 check=yes
 today=`date +%Y%m%d`
 pmode='no'
+tmpdir="../#release_tmp.$$"	# tmp work directory
 
 # Restore previous Version information
 RESTORE_VERSION()
@@ -155,6 +164,15 @@ if [ "X$methods" = "X" ]; then
     methods="tar md5"
 fi
 
+# Create the temporay work directory.
+if mkdir $tmpdir; then
+    echo "temporary work directory for release.  "\
+         "Can be deleted after release completes." > $tmpdir/READEME
+else
+    echo "Failed to mkdir tmpdir($tmpdir)"
+    exit 1
+fi
+
 # setup restoration in case of abort.
 trap RESTORE_VERSION 0
 
@@ -176,7 +194,6 @@ if [ ! -d $DEST ]; then
     exit 1
 fi
 
-
 # Check the validity of the MANIFEST file.
 bin/chkmanifest || fail=yes
 if [ "X$fail" = "Xyes" ]; then
@@ -188,13 +205,12 @@ if [ "X$fail" = "Xyes" ]; then
 fi
 
 # Create a manifest that contains only files for distribution.
-MANIFEST=/tmp/H5_MANIFEST.$$
+MANIFEST=$tmpdir/H5_MANIFEST
 grep '^\.' MANIFEST | grep -v _DO_NOT_DISTRIBUTE_ >$MANIFEST
 
 # Prepare the source tree for a release.
-test -h ../$HDF5_VERS && rm ../$HDF5_VERS
-ln -s `pwd` ../$HDF5_VERS || exit 1
-mv Makefile ../Makefile.x 2>/dev/null #might fail
+ln -s `pwd` $tmpdir/$HDF5_VERS || exit 1
+mv Makefile $tmpdir/Makefile.x 2>/dev/null #might fail
 cp -p Makefile.dist Makefile
 
 # Update README.txt and release_docs/RELEASE.txt with release information.
@@ -212,7 +228,7 @@ cp release_docs/HISTORY.txt release_docs/RELEASE.txt doc/html/ADGuide/.
 # Create the tar file
 test "$verbose" && echo "   Running tar..." 1>&2
 ( \
-    cd ..; \
+    cd $tmpdir; \
     tar cf $HDF5_VERS.tar $HDF5_VERS/Makefile \
 	`sed 's/^\.\//hdf5-'$VERS'\//' $MANIFEST` || exit 1 \
 )
@@ -221,37 +237,40 @@ test "$verbose" && echo "   Running tar..." 1>&2
 for comp in $methods; do
     case $comp in
 	tar)
-	    cp -p ../$HDF5_VERS.tar $DEST/$HDF5_VERS.tar;;
+	    cp -p $tmpdir/$HDF5_VERS.tar $DEST/$HDF5_VERS.tar
+	    ;;
 	compress)
 	    test "$verbose" && echo "   Running compress..." 1>&2
-	    compress -c <../$HDF5_VERS.tar >$DEST/$HDF5_VERS.tar.Z;;
+	    compress -c <$tmpdir/$HDF5_VERS.tar >$DEST/$HDF5_VERS.tar.Z
+	    ;;
 	gzip)
 	    test "$verbose" && echo "   Running gzip..." 1>&2
-	    gzip -9 <../$HDF5_VERS.tar >$DEST/$HDF5_VERS.tar.gz;;
+	    gzip -9 <$tmpdir/$HDF5_VERS.tar >$DEST/$HDF5_VERS.tar.gz
+	    ;;
 	bzip2)
 	    test "$verbose" && echo "   Running bzip2..." 1>&2
-	    bzip2 -9 <../$HDF5_VERS.tar >$DEST/$HDF5_VERS.tar.bz2;;
+	    bzip2 -9 <$tmpdir/$HDF5_VERS.tar >$DEST/$HDF5_VERS.tar.bz2
+	    ;;
 	md5)
 	    test "$verbose" && echo "   Creating checksum..." 1>&2
-	    (  cd .. && md5sum $HDF5_VERS.tar >$HDF5_VERS.tar.md5 )
-	    cp -p ../$HDF5_VERS.tar.md5 $DEST/$HDF5_VERS.tar.md5;;
+	    (cd $tmpdir; md5sum $HDF5_VERS.tar ) > $DEST/$HDF5_VERS.tar.md5
+	    ;;
     esac
 done
 
 # Copy the RELEASE.txt to the release area.
 cp release_docs/RELEASE.txt $DEST/$HDF5_VERS-RELEASE.txt
 
-# Remove temporary things
-test -f ../Makefile.x && mv ../Makefile.x Makefile
-rm -f $MANIFEST
-rm -f ../$HDF5_VERS
-rm -f ../$HDF5_VERS.tar
-rm -f ../$HDF5_VERS.tar.md5
+# Restore previous Makefile if existed.
+test -f $tmpdir/Makefile.x && mv $tmpdir/Makefile.x Makefile
 
 # Restore OLD version information, then no need for trap.
 if [ X$pmode = Xyes ]; then
     RESTORE_VERSION
     trap 0
 fi
+
+# Remove temporary things
+rm -rf $tmpdir
 
 exit 0
diff --git a/bin/snapshot b/bin/snapshot
--- a/bin/snapshot
+++ b/bin/snapshot
@@ -1,5 +1,6 @@
 #!/bin/sh
 #
+# Copyright by The HDF Group.
 # Copyright by the Board of Trustees of the University of Illinois.
 # All rights reserved.
 #
@@ -9,14 +10,14 @@
 # of the source code distribution tree; Copyright.html can be found at the
 # root level of an installed copy of the electronic HDF5 document set and
 # is linked from the top-level documents page.  It can also be found at
-# http://hdf.ncsa.uiuc.edu/HDF5/doc/Copyright.html.  If you do not have
-# access to either file, you may request a copy from hdfhelp@ncsa.uiuc.edu.
+# http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have
+# access to either file, you may request a copy from help@hdfgroup.org.
 
 # This script should be run nightly from cron.  It checks out hdf5
-# from the CVS source tree and compares it against the previous
+# from the source repository and compares it against the previous
 # snapshot.  If anything significant changed then a new snapshot is
 # created, the minor version number is incremented, and the change is
-# checked back into the CVS repository.
+# checked back into the source repository.
 #
 
 # function definitions
@@ -29,6 +30,14 @@ EXIT_BANNER()
 {
 TIMESTAMP "Exit $PROGNAME with status=$?"
 }
+
+# Show current total disk usage.
+DISKUSAGE()
+{
+    du -ks | \
+    ( read x y; echo "Disk Usage=$x KB" )
+}
+
 
 # MAIN
 # SGI /bin/sh replaces $0 as function name if used in a function.
@@ -44,14 +53,13 @@ uname -a
 # setup exit banner message
 trap EXIT_BANNER 0
 
-# Dump environment variables
-echo ===Dumping environment variables===
+# Dump environment variables before option parsing
+echo ===Dumping environment variables before option parsing ===
 printenv | sort
-echo ===Done Dumping environment variables===
+echo ===Done Dumping environment variables before option parsing ===
 
-# Where are the snapshots stored?
-ARCHIVES_default=/afs/ncsa/ftp/HDF/pub/outgoing/hdf5/snapshots
-ARCHIVES=$ARCHIVES_default
+# snapshots release directory.  Default relative to $BASEDIR.
+ReleaseDir_default=release_dir
 
 # Where is the zlib library?
 # At NCSA, half of the machines have it in /usr/lib, the other half at
@@ -64,6 +72,9 @@ METHODS="gzip bzip2 md5"
 
 # Use User's MAKE if set.  Else use generic make.
 MAKE=${MAKE:-make}
+
+# Default check action.
+CHECKVAL=check
 
 #
 # Command options
@@ -175,15 +186,18 @@ while [ $# -gt 0 ] ; do
 	    fi
 	    ZLIB="$1"
 	    ;;
-	archive)
+	releasedir)
 	    shift
 	    if [ $# -lt 1 ]; then
-		echo "Archive pathname missing"
+		echo "Release directory name missing"
 		errcode=1
 		cmd="help"
 		break
 	    fi
-	    ARCHIVES="$1"
+	    ReleaseDir="$1"
+	    ;;
+	check-vfd)
+	    CHECKVAL=check-vfd
 	    ;;
 	--*)
 	    OP_CONFIGURE="$OP_CONFIGURE $1"
@@ -208,16 +222,21 @@ while [ $# -gt 0 ] ; do
     shift
 done
 
+# Dump environment variables after option parsing
+echo ===Dumping environment variables after option parsing ===
+printenv | sort
+echo ===Done Dumping environment variables after option parsing ===
+
 if [ "$cmd" = help ]; then
     set -
     cat <<EOF
 Usage: $PROGNAME [all] [checkout] [diff] [test] [srcdir] [release] [help]
 	[clean] [distclean] [echo] [deploy <dir>] [deploydir <dir>]
-	[zlib <zlib_path>] [archive <arch_path>] [srcdirname <dir>]
+	[zlib <zlib_path>] [releasedir <dir>] [srcdirname <dir>] [check-vfd]
 	[op-configure <option>] [--<option>]
     all:      Run all commands (checkout, test & release)
               [Default is all]
-    checkout: Run cvs checkout
+    checkout: Run source checkout
     diff:     Run diff on current and previous versions.  Exit 0 if
               no significant differences are found.  Otherwise, non-zero.
     deploy:   deploy binary to directory <dir>
@@ -245,9 +264,11 @@ Usage: $PROGNAME [all] [checkout] [diff] [test] [srcdir] [release] [help]
     zlib <zlib_path>:
               Use <zlib_path> as the ZLIB locations
               [Default is $ZLIB_default]
-    archive <arch_path>:
-              Use <arch_path> as the release ARCHIVE area
-              [Default is $ARCHIVES_default]
+    releasedir <dir>:
+              Use <dir> as the release directory
+              [Default is $ReleaseDir_default]
+    check-vfd:
+	      Run make check-vfd instead of just make check.
     op-configure <option>:
               Pass <option> to the configure command
               E.g., "snapshot op-configure --enable-parallel"
@@ -282,11 +303,12 @@ fi
 
 CURRENT=${BASEDIR}/current
 PREVIOUS=${BASEDIR}/previous
+ReleaseDir=${ReleaseDir:=${BASEDIR}/${ReleaseDir_default}}
 HOSTNAME=`hostname | cut -f1 -d.`	# no domain part
 if [ $H5VERSION != hdf5 ]; then
-    CVSVERSION="-r $H5VERSION"
+    SVNVERSION="hdf5/branches/$H5VERSION"
 else
-    CVSVERSION=				# use the default (main) version
+    SVNVERSION=hdf5/trunk		# use the default (trunk) version
 fi
 
 # Try finding a version of diff that supports the -I option too.
@@ -297,13 +319,13 @@ for d in `echo $PATH | sed -e 's/:/ /g'` ; do
 done
 
 #=============================
-# Run CVS checkout
+# Run source checkout
 #=============================
 if [ "$cmd" = "all" -o -n "$cmdcheckout" ]; then
     TIMESTAMP "checkout"
     # If there is a Makefile in ${CURRENT}, the last test done in it
     # has not been distclean'ed.  They would interfere with other
-    # --srcdir build since make considers the files in ${CURRENT} 
+    # --srcdir build since make considers the files in ${CURRENT}
     # take precedence over files in its own build-directory.  Run
     # a "make distclean" to clean them all out.  This is not really
     # part of the "checkout" functions but this is the most convenient
@@ -311,14 +333,10 @@ if [ "$cmd" = "all" -o -n "$cmdcheckout" ]; then
     # regardless of the return code of distclean.
     ( cd ${CURRENT}; test -f Makefile && ${MAKE} distclean)
 
-    # verify proper cvs setting
-    if [ -z "$CVSROOT" ]; then
-	echo "CVSROOT not defined!" 1>&2
-	exit 1
-    fi
-    # Check out the current version from CVS
-    (cd $BASEDIR; cvs -Q co -P -d current ${CVSVERSION} hdf5 ) || exit 1
-fi # Do CVS checkout
+    SVNROOT=http://svn.hdfgroup.uiuc.edu
+    # Check out the current version from source repository.
+    (cd $BASEDIR; svn -q co ${SVNROOT}/${SVNVERSION} current ) || exit 1
+fi # Do source checkout
 
 
 #=============================
@@ -386,15 +404,15 @@ if [ "$cmd" = "all" -o -n "$cmdtest" -o -n "$cmddiff" ]; then
 	    TIMESTAMP "configure" && \
 	    ${srcdir:+${CURRENT}/}${CONFIGURE} && \
 	    TIMESTAMP "make" && \
-	    ${MAKE} && \
-	    TIMESTAMP "check" && \
-	    ${MAKE} check && \
+	    ${MAKE} && DISKUSAGE \
+	    TIMESTAMP ${CHECKVAL} && \
+	    ${MAKE} ${CHECKVAL} && DISKUSAGE \
 	    TIMESTAMP "install" && \
-	    ${MAKE} install install-doc && \
+	    ${MAKE} install-all && DISKUSAGE \
 	    TIMESTAMP "check-install" && \
-	    ${MAKE} check-install && \
+	    ${MAKE} check-install && DISKUSAGE \
 	    TIMESTAMP "uninstall" && \
-	    ${MAKE} uninstall uninstall-doc); then
+	    ${MAKE} uninstall-all) && DISKUSAGE ; then
 	    :
 	else
 	    errcode=$?
@@ -411,7 +429,12 @@ fi # Test the HDF5 library
 if [ -n "$DEPLOYDIRNAME" ]; then
     if [ "$snapshot" = "yes" ]; then
 	TIMESTAMP "deploy"
-	if (cd ${TESTDIR} && ${CURRENT}/bin/deploy ${deploydir}/${DEPLOYDIRNAME}); then
+        if (cd ${TESTDIR} &&
+            ${CURRENT}/bin/deploy ${deploydir}/${DEPLOYDIRNAME} && \
+            TIMESTAMP "clean" && \
+            ${MAKE} clean && \
+            TIMESTAMP "check-install prefix=${deploydir}/${DEPLOYDIRNAME}" && \
+            ${MAKE} check-install prefix=${deploydir}/${DEPLOYDIRNAME}); then
 	    :	#continue
 	else
 	    errcode=$?
@@ -422,7 +445,7 @@ fi # Deploy
 
 
 #=============================
-# Run Release snapshot, update version, and commit to cvs and tag
+# Run Release snapshot, update version, and commit to source repository
 #=============================
 if [ "$cmd" = "all" -o -n "$cmdrel" ]; then
     if [ "$snapshot" = "yes" ]; then
@@ -430,20 +453,21 @@ if [ "$cmd" = "all" -o -n "$cmdrel" ]; then
 	(cd ${CURRENT} && ${MAKE} distclean)
 	(
 	    # Turn on exit on error in the sub-shell so that it does not
-	    # cvs commit if errors encounter here.
+	    # commit source if errors encounter here.
 	    set -e
 	    cd ${CURRENT}
-	    bin/release -d $ARCHIVES $METHODS
 	    RELEASE_VERSION="`perl bin/h5vers -v`"
+	    echo "Making snapshot release ($RELEASE_VERSION) to ${ReleaseDir}..."
+	    bin/release -d $ReleaseDir $METHODS
 	    perl bin/h5vers -i
-	    cvs -Q commit -m "Snapshot $RELEASE_VERSION"
+	    svn -q commit -m "Snapshot $RELEASE_VERSION"
 	)
 	errcode=$?
     fi
 
     # Replace the previous version with the current version.
     # Should check if the errcode of the release process but there
-    # are other failures after release was done (e.g. h5vers or cvs failures)
+    # are other failures after release was done (e.g. h5vers or svn failures)
     # that should allow the replacement to occure.
     rm -rf ${PREVIOUS}
     mv ${CURRENT} ${PREVIOUS}
diff --git a/tools/h5dump/testh5dump.sh.in b/tools/h5dump/testh5dump.sh.in
--- a/tools/h5dump/testh5dump.sh.in
+++ b/tools/h5dump/testh5dump.sh.in
@@ -1,5 +1,6 @@
 #! /bin/sh
 #
+# Copyright by The HDF Group.
 # Copyright by the Board of Trustees of the University of Illinois.
 # All rights reserved.
 #
@@ -9,8 +10,8 @@
 # of the source code distribution tree; Copyright.html can be found at the
 # root level of an installed copy of the electronic HDF5 document set and
 # is linked from the top-level documents page.  It can also be found at
-# http://hdf.ncsa.uiuc.edu/HDF5/doc/Copyright.html.  If you do not have
-# access to either file, you may request a copy from hdfhelp@ncsa.uiuc.edu.
+# http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have
+# access to either file, you may request a copy from help@hdfgroup.org.
 #
 # Tests for the h5dump tool
 
@@ -20,8 +21,15 @@ USE_FILTER_DEFLATE="@USE_FILTER_DEFLATE@"
 USE_FILTER_SHUFFLE="@USE_FILTER_SHUFFLE@"
 USE_FILTER_FLETCHER32="@USE_FILTER_FLETCHER32@"
 
-DUMPER=h5dump               # The tool name
-DUMPER_BIN=`pwd`/$DUMPER    # The path of the tool binary
+DUMPER=h5dump                     # The tool name
+DUMPER_BIN=`pwd`/$DUMPER          # The path of the tool binary
+TESTDIR=`pwd`/../testfiles
+
+H5DIFF=../h5diff/h5diff           # The h5diff tool name 
+H5DIFF_BIN=`pwd`/$H5DIFF          # The path of the h5diff  tool binary
+
+H5IMPORT=../h5import/h5import     # The h5import tool name 
+H5IMPORT_BIN=`pwd`/$H5IMPORT      # The path of the h5import  tool binary
 
 CMP='cmp -s'
 DIFF='diff -c'
@@ -34,7 +42,7 @@ if test -z "$srcdir"; then
    srcdir=.
 fi
 
-test -d ../testfiles || mkdir ../testfiles
+test -d $TESTDIR || mkdir $TESTDIR
 
 # Print a line-line message left justified in a field of 70 characters
 # beginning with the word "Testing".
@@ -53,54 +61,125 @@ TESTING() {
 # non-zero value.
 #
 TOOLTEST() {
-   expect="$srcdir/../testfiles/$1"
-   actual="../testfiles/`basename $1 .ddl`.out"
-   actual_err="../testfiles/`basename $1 .ddl`.err"
-   shift
 
-   # Run test.
-   TESTING $DUMPER $@
-   (
-      echo "#############################"
-      echo "Expected output for '$DUMPER $@'" 
-      echo "#############################"
-      cd $srcdir/../testfiles
-      $RUNSERIAL $DUMPER_BIN $@
-   ) >$actual 2>$actual_err
-   cat $actual_err >> $actual
+    expect="$srcdir/../testfiles/$1"
+    actual="../testfiles/`basename $1 .ddl`.out"
+    actual_err="../testfiles/`basename $1 .ddl`.err"
+    shift
 
+    # Run test.
+    TESTING $DUMPER $@
+    (
+	cd $srcdir/../testfiles
+	$RUNSERIAL $DUMPER_BIN $@
+    ) >$actual 2>$actual_err
+    cat $actual_err >> $actual
 
-   if [ ! -f $expect ]; then
-    # Create the expect file if it doesn't yet exist.
-    echo " CREATED"
-    cp $actual $expect
-   elif $CMP $expect $actual; then
-      echo " PASSED"
-   else
-      echo "*FAILED*"
-      echo "    Expected result (*.ddl) differs from actual result (*.out)"
-      nerrors="`expr $nerrors + 1`"
-      test yes = "$verbose" && $DIFF $expect $actual |sed 's/^/    /'
-   fi
+    if [ ! -f $expect ]; then
+        echo "*FAILED*"
+	echo "    $expect missing"
+        nerrors="`expr $nerrors + 1`"
+    else
+	# Skip the first three lines, which are label lines, before cmp.
+        if tail +4l $expect | $CMP - $actual; then
+	    echo " PASSED"
+        else
+	    echo "*FAILED*"
+	    echo "    Expected result (*.ddl) differs from actual result (*.out)"
+	    nerrors="`expr $nerrors + 1`"
+	    test yes = "$verbose" && $DIFF $expect $actual |sed 's/^/    /'
+        fi
+    fi
 
-   # Clean up output file
-   if test -z "$HDF5_NOCLEANUP"; then
-      rm -f $actual $actual_err
-   fi
+    # Clean up output file
+    if test -z "$HDF5_NOCLEANUP"; then
+	rm -f $actual $actual_err
+    fi
+
 }
 
 
 # Print a "SKIP" message
 SKIP() {
-	 TESTING $DUMPER $@
-	  echo  " -SKIP-"
+     TESTING $DUMPER $@
+      echo  " -SKIP-"
 }
   
 
+# Print a line-line message left justified in a field of 70 characters
+# beginning with the word "Verifying".
+#
+PRINT_H5DIFF() {
+ SPACES="                                                               "
+ echo " Running h5diff $* $SPACES" | cut -c1-70 | tr -d '\012'
+}
 
+
+# Call the h5diff tool
+#
+DIFFTEST() 
+{
+    PRINT_H5DIFF  $@
+    (
+     cd $srcdir/../testfiles
+     if [ "`uname -s`" = "TFLOPS O/S" ]; then
+      $RUNSERIAL $H5DIFF_BIN $@ -q
+     else
+      $RUNSERIAL $H5DIFF_BIN "$@" -q
+     fi
+    )
+    RET=$?
+    if [ $RET != 0 ] ; then
+         echo "*FAILED*"
+         nerrors="`expr $nerrors + 1`"
+    else
+         echo " PASSED"
+    fi
+        
+}
+
+# Print a line-line message left justified in a field of 70 characters
+# beginning with the word "Verifying".
+#
+PRINT_H5IMPORT() {
+ SPACES="                                                               "
+ echo " Running h5import $* $SPACES" | cut -c1-70 | tr -d '\012'
+}
+
+# Call the h5import tool
+#
+IMPORTTEST() 
+{
+    # remove the output hdf5 file if it exists
+    hdf5_file="$srcdir/../testfiles/$5"
+    if [ -f $hdf5_file ]; then
+     rm -f $hdf5_file
+    fi
+
+    PRINT_H5IMPORT  $@
+    (
+     cd $srcdir/../testfiles
+     if [ "`uname -s`" = "TFLOPS O/S" ]; then
+      $RUNSERIAL $H5IMPORT_BIN $@
+     else
+      $RUNSERIAL $H5IMPORT_BIN "$@" 
+     fi
+    )
+    RET=$?
+    if [ $RET != 0 ] ; then
+         echo "*FAILED*"
+         nerrors="`expr $nerrors + 1`"
+    else
+         echo " PASSED"
+    fi
+        
+}
+
+
+    
 ##############################################################################
 ##############################################################################
-###			  T H E   T E S T S                                ###
+###           T H E   T E S T S                                ###
 ##############################################################################
 ##############################################################################
 
@@ -188,9 +267,9 @@ TOOLTEST tempty.ddl tempty.h5
 TOOLTEST tgrp_comments.ddl tgrp_comments.h5
 
 # test the --filedriver flag
-#TOOLTEST tsplit_file.ddl --filedriver=split tsplit_file
+TOOLTEST tsplit_file.ddl --filedriver=split tsplit_file
 TOOLTEST tfamily.ddl --filedriver=family tfamily%05d.h5
-#TOOLTEST tmulti.ddl --filedriver=multi tmulti
+TOOLTEST tmulti.ddl --filedriver=multi tmulti
 
 # test for files with group names which reach > 1024 bytes in size
 TOOLTEST tlarge_objname.ddl -w157 tlarge_objname.h5
@@ -252,7 +331,6 @@ TOOLTEST tstring2.ddl -r -d str4 tstr3.h5
 TOOLTEST tindicesyes.ddl taindices.h5
 TOOLTEST tindicesno.ddl -y taindices.h5
 
-
 # tests for filters
 # SZIP
 option="-H -p -d szip tfilters.h5"
@@ -294,6 +372,35 @@ TOOLTEST tuserfilter.ddl -H  -p -d myfilter  tfilters.h5
 
 # test for displaying objects with very long names
 TOOLTEST tlonglinks.ddl tlonglinks.h5
+
+# dimensions over 4GB, print boundary 
+TOOLTEST tbigdims.ddl -d dset4gb -s 4294967284 -c 22 tbigdims.h5
+
+# hyperslab read
+TOOLTEST thyperslab.ddl thyperslab.h5
+
+#
+
+# test for long double (some systems do not have long double)
+#TOOLTEST tldouble.ddl tldouble.h5
+
+# test for binary output
+TOOLTEST   tbin1.ddl -d array  -o $TESTDIR/out1.bin -b LE     tbinary.h5
+TOOLTEST   tbin2.ddl -d float  -o $TESTDIR/out2.bin -b BE     tbinary.h5
+
+# the MEMORY test can be validated with h5import/h5diff
+TOOLTEST   tbin3.ddl -d integer -o $TESTDIR/out3.bin -b MEMORY tbinary.h5
+IMPORTTEST $TESTDIR/out3.bin -c out3.h5import -o $TESTDIR/out3.h5
+DIFFTEST   tbinary.h5 $TESTDIR/out3.h5 /integer /integer
+
+TOOLTEST   tbin4.ddl -d double  -o $TESTDIR/out4.bin -b FILE   tbinary.h5
+   
+# Clean up binary output files
+if test -z "$HDF5_NOCLEANUP"; then
+ rm -f $TESTDIR/out[1-4].bin
+ rm -f $TESTDIR/out3.h5
+fi
+
 
 
 if test $nerrors -eq 0 ; then
