hdf5-1.4.4

diff --git a/bin/snapshot b/bin/snapshot
--- a/bin/snapshot
+++ b/bin/snapshot
@@ -1,4 +1,17 @@
 #!/bin/sh
+#
+# Copyright by the Board of Trustees of the University of Illinois.
+# All rights reserved.
+#
+# This file is part of HDF5.  The full HDF5 copyright notice, including
+# terms governing use, modification, and redistribution, is contained in
+# the files COPYING and Copyright.html.  COPYING can be found at the root
+# of the source code distribution tree; Copyright.html can be found at the
+# root level of an installed copy of the electronic HDF5 document set and
+# is linked from the top-level documents page.  It can also be found at
+# http://hdf.ncsa.uiuc.edu/HDF5/doc/Copyright.html.  If you do not have
+# access to either file, you may request a copy from hdfhelp@ncsa.uiuc.edu.
+#
 echo "====================================="
 echo "$0 $*"
 echo "====================================="
@@ -21,10 +34,11 @@ PATH="/usr/local/bin:$PATH"
 ARCHIVES_default=/afs/ncsa/ftp/HDF/pub/outgoing/hdf5/snapshots
 ARCHIVES=$ARCHIVES_default
 
-# Where are the HDF4 library?
-# At NCSA, the standard place to find HDF4 software is in /usr/ncsa/.
-HDF4LIB_default="/usr/ncsa/include,/usr/ncsa/lib"
-HDF4LIB=$HDF4LIB_default
+# Where is the zlib library?
+# At NCSA, half of the machines have it in /usr/lib, the other half at
+# /usr/ncsa/lib.  Leave it unset.
+ZLIB_default=
+ZLIB=$ZLIB_default
 
 # What compression methods to use?
 METHODS="gzip bzip2"
@@ -50,6 +64,10 @@ while [ $# -gt 0 ] ; do
 	    ;;
 	checkout)
 	    cmdcheckout="checkout"
+	    cmd=""
+	    ;;
+	diff)
+	    cmddiff="diff"
 	    cmd=""
 	    ;;
 	test)
@@ -82,15 +100,15 @@ while [ $# -gt 0 ] ; do
 	    cmd="help"
 	    break
 	    ;;
-	hdf4)
+	zlib)
 	    shift
 	    if [ $# -lt 1 ]; then
-		echo "HDF4LIB information missing"
+		echo "ZLIB information missing"
 		errcode=1
 		cmd="help"
 		break
 	    fi
-	    HDF4LIB="$1"
+	    ZLIB="$1"
 	    ;;
 	archive)
 	    shift
@@ -128,12 +146,14 @@ done
 if [ "$cmd" = help ]; then
     set -
     cat <<EOF
-Usage: $0 [all] [checkout] [test] [srcdir] [release] [help]
-          [hdf4 <hdf4lib_path>] [archive <arch_path>] [dir <dir>]
+Usage: $0 [all] [checkout] [diff] [test] [srcdir] [release] [help]
+          [zlib <zlib_path>] [archive <arch_path>] [dir <dir>]
 	  [op-configure <option>] [--<option>]
     all:      Run all commands (checkout, test & release)
               [Default is all]
     checkout: Run cvs checkout
+    diff:     Run diff on current and previous versions.  Exit 0 if
+              no significant differences are found.  Otherwise, non-zero.
     test:     Run test
     release:  Run release
     clean:    Run make clean
@@ -147,9 +167,9 @@ Usage: $0 [all] [checkout] [test] [srcdir] [release] [help]
               E.g., "snapshot srcdir srcdirname -xx" uses hostname-xx
               [Default is hostname]
     help:     Print this message
-    hdf4 <hdf4lib_path>:
-              Use <hdf4lib_path> as the HDF4LIB locations
-              [Default is $HDF4LIB_default]
+    zlib <zlib_path>:
+              Use <zlib_path> as the ZLIB locations
+              [Default is $ZLIB_default]
     archive <arch_path>:
               Use <arch_path> as the release ARCHIVE area
               [Default is $ARCHIVES_default]
@@ -165,15 +185,20 @@ EOF
     exit $errcode
 fi
 
-# Setup the proper configure option (--with-hdf4) to use hdf4 library
-# provide HDF4LIB is non-empty.
-HDF4LIB=${HDF4LIB:+"--with-hdf4="$HDF4LIB}
-CONFIGURE="./configure $HDF4LIB $OP_CONFIGURE"
+# Setup the proper configure option (--with-zlib) to use zlib library
+# provide ZLIB is non-empty.
+ZLIB=${ZLIB:+"--with-zlib="$ZLIB}
+CONFIGURE="./configure $ZLIB $OP_CONFIGURE"
 
 # Execute the requests
 snapshot=yes
 
-H5VERSION=hdf5_1_4
+if [ -f bin/snapshot_version ]; then
+    . bin/snapshot_version
+else
+    H5VERSION=hdf5
+fi
+
 BASEDIR=${HOME}/snapshots-${H5VERSION}
 CURRENT=${BASEDIR}/current
 PREVIOUS=${BASEDIR}/previous
@@ -218,7 +243,7 @@ fi # Do CVS checkout
 #=============================
 # Run Test the HDF5 library
 #=============================
-if [ "$cmd" = "all" -o -n "$cmdtest" ]; then
+if [ "$cmd" = "all" -o -n "$cmdtest" -o -n "$cmddiff" ]; then
     # setup if srcdir is used.
     if [ -z "$srcdir" ]; then
 	TESTDIR=${CURRENT}
@@ -259,10 +284,19 @@ if [ "$cmd" = "all" -o -n "$cmdtest" ]; then
 		    :	#continue
 		else
 		    snapshot=yes
-		    # Don't break because we want to see all the diffs.
 		    break
 		fi
 	    done
+	fi
+    fi
+
+    # if diff is choosen, exit 0 if no significant differences are found.
+    # otherwise, exit 1.  This includes cases of other failures.
+    if [ -n "$cmddiff" ]; then
+	if [ $snapshot = no ]; then
+	    exit 0
+	else
+	    exit 1
 	fi
     fi
 
@@ -273,6 +307,7 @@ if [ "$cmd" = "all" -o -n "$cmdtest" ]; then
 	    ${MAKE} && \
 	    ${MAKE} check && \
 	    ${MAKE} install install-doc && \
+	    ${MAKE} check-install && \
 	    ${MAKE} uninstall uninstall-doc); then
 	    :
 	else
