hdf5-1.8.4

diff --git a/tools/h5repack/h5repack.sh.in b/tools/h5repack/h5repack.sh.in
--- a/tools/h5repack/h5repack.sh.in
+++ b/tools/h5repack/h5repack.sh.in
@@ -54,6 +54,7 @@ FILE13=h5repack_soffset.h5
 FILE14=h5repack_layouto.h5      # A file with an older version of the layout message
                                 # (copy of test/tlayouto.h5)
 FILE15=h5repack_named_dtypes.h5
+FILE16=tfamily%05d.h5           # located in common testfiles folder
 
 
 nerrors=0
@@ -95,11 +96,7 @@ SKIP() {
 DIFFTEST() 
 {
     VERIFY  $@
-    if [ "`uname -s`" = "TFLOPS O/S" ]; then
-     $RUNSERIAL $H5DIFF_BIN -q  $@ 
-    else
-     $RUNSERIAL $H5DIFF_BIN -q  "$@" 
-    fi
+    $RUNSERIAL $H5DIFF_BIN -q  "$@" 
     RET=$?
     if [ $RET != 0 ] ; then
          echo "*FAILED*"
@@ -115,55 +112,68 @@ DIFFTEST()
 TOOLTEST() 
 {
     # Run test.
-    # Tflops interprets "$@" as "" when no parameter is given (e.g., the
-    # case of missing file name).  Changed it to use $@ till Tflops fixes it.
     TESTING $H5REPACK $@
 
     infile=$srcdir/testfiles/$1
     path=`pwd`
     outfile=$path/out.$1
     shift
-    if [ "`uname -s`" = "TFLOPS O/S" ]; then
-     $RUNSERIAL $H5REPACK_BIN $@ $infile $outfile
-    else
-     $RUNSERIAL $H5REPACK_BIN "$@" $infile $outfile
-    fi
-
+    $RUNSERIAL $H5REPACK_BIN "$@" $infile $outfile
     RET=$?
     if [ $RET != 0 ] ; then
-     echo "*FAILED*"
-     nerrors="`expr $nerrors + 1`"
+	echo "*FAILED*"
+	nerrors="`expr $nerrors + 1`"
     else
-     echo " PASSED"
-     DIFFTEST $infile $outfile
+	echo " PASSED"
+	DIFFTEST $infile $outfile
     fi
     rm -f $outfile
 }
 
+# same as TOOLTEST, but it uses the old syntax -i input_file -o output_file
+#
 TOOLTEST0() 
 {
     # Run test.
-    # Tflops interprets "$@" as "" when no parameter is given (e.g., the
-    # case of missing file name).  Changed it to use $@ till Tflops fixes it.
     TESTING $H5REPACK $@
 
     infile=$srcdir/testfiles/$1
     path=`pwd`
     outfile=$path/out.$1
     shift
-    if [ "`uname -s`" = "TFLOPS O/S" ]; then
-     $RUNSERIAL $H5REPACK_BIN -i $infile -o $outfile $@
-    else
-     $RUNSERIAL $H5REPACK_BIN -i $infile -o $outfile "$@"
-    fi
-
+    $RUNSERIAL $H5REPACK_BIN -i $infile -o $outfile "$@"
     RET=$?
     if [ $RET != 0 ] ; then
-     echo "*FAILED*"
-     nerrors="`expr $nerrors + 1`"
+        echo "*FAILED*"
+        nerrors="`expr $nerrors + 1`"
     else
-     echo " PASSED"
-     DIFFTEST $infile $outfile
+        echo " PASSED"
+        DIFFTEST $infile $outfile
+    fi
+    rm -f $outfile
+}
+
+
+# same as TOOLTEST, but it uses the common testfiles at $srcdir/../testfiles/
+# used to test the family driver, where these files reside
+#
+TOOLTEST1() 
+{
+    # Run test.
+    TESTING $H5REPACK $@
+
+    infile=$srcdir/../testfiles/$1
+    path=`pwd`
+    outfile=$path/out.$1
+    shift
+    $RUNSERIAL $H5REPACK_BIN "$@" $infile $outfile
+    RET=$?
+    if [ $RET != 0 ] ; then
+	echo "*FAILED*"
+	nerrors="`expr $nerrors + 1`"
+    else
+	echo " PASSED"
+	DIFFTEST $infile $outfile
     fi
     rm -f $outfile
 }
@@ -513,6 +523,9 @@ TOOLTEST $FILE1 -f GZIP=1
 
 # Check repacking file with committed datatypes in odd configurations
 TOOLTEST $FILE15
+
+# tests family driver (file is located in common testfiles folder, uses TOOLTEST1
+TOOLTEST1 $FILE16
 
 if test $nerrors -eq 0 ; then
    echo "All $H5REPACK tests passed."
