hdf5-1.8.12.

diff --git a/tools/h5repack/h5repack.sh.in b/tools/h5repack/h5repack.sh.in
--- a/tools/h5repack/h5repack.sh.in
+++ b/tools/h5repack/h5repack.sh.in
@@ -42,6 +42,7 @@ H5DIFF_BIN=`pwd`/$H5DIFF        # The path of the h5diff tool binary
 H5DUMP=../h5dump/h5dump         # The h5dump tool name
 H5DUMP_BIN=`pwd`/$H5DUMP        # The path of the h5dump tool binary
 
+RM='rm -rf'
 GREP='grep'
 CP='cp'
 DIRNAME='dirname'
@@ -117,10 +118,15 @@ $SRC_TOOLS_TESTFILES/tfamily00010.h5
 "
 
 LIST_OTHER_TEST_FILES="
+$SRC_H5REPACK_TESTFILES/h5repack-help.txt
 $SRC_H5REPACK_TESTFILES/h5repack_ext.bin
 $SRC_H5REPACK_TESTFILES/ublock.bin
 $SRC_H5REPACK_TESTFILES/h5repack.info
-$SRC_TOOLS_TESTFILES/h5repack_filters.h5.ddl
+$SRC_H5REPACK_TESTFILES/deflate_limit.h5repack_layout.h5.ddl
+$SRC_H5REPACK_TESTFILES/h5repack_layout.h5.ddl
+$SRC_H5REPACK_TESTFILES/h5repack_filters.h5.tst
+$SRC_H5REPACK_TESTFILES/h5repack_layout.h5-plugin_test.ddl
+$SRC_H5REPACK_TESTFILES/plugin_test.h5repack_layout.h5.tst
 "
 
 #
@@ -154,6 +160,19 @@ COPY_TESTFILES_TO_TESTDIR()
             fi
         fi
     done
+}
+
+CLEAN_TESTFILES_AND_TESTDIR()
+{
+    # skip rm if srcdir is same as destdir
+    # this occurs when build/test performed in source dir and
+    # make cp fail
+    SDIR=`$DIRNAME $tstfile`
+    INODE_SDIR=`$LS -i -d $SDIR | $AWK -F' ' '{print $1}'`
+    INODE_DDIR=`$LS -i -d $TESTDIR | $AWK -F' ' '{print $1}'`
+    if [ "$INODE_SDIR" != "$INODE_DDIR" ]; then
+        $RM $TESTDIR
+    fi
 }
 
 # Print a $* message left justified in a field of 70 characters
@@ -201,7 +220,7 @@ DIFFTEST()
     fi
         
 }
-          
+
 # Call h5repack
 #
 
@@ -435,7 +454,7 @@ TOOLTEST1()
 #
 TOOLTESTV() 
 {
-    expect="$TESTDIR/$2.ddl"
+    expect="$TESTDIR/$2.tst"
     actual="$TESTDIR/`basename $2 .ddl`.out"
     actual_err="$TESTDIR/`basename $2 .ddl`.err"
 
@@ -463,6 +482,54 @@ TOOLTESTV()
     cat $actual_err >> $actual
 
     VERIFY output from $H5REPACK $@
+    if cmp -s $expect $actual; then
+     echo " PASSED"
+    else
+     echo "*FAILED*"
+     echo "    Expected result (*.tst) differs from actual result (*.out)"
+     nerrors="`expr $nerrors + 1`"
+     test yes = "$verbose" && diff -c $expect $actual |sed 's/^/    /'
+    fi
+    
+   rm -f $actual $actual_err
+   rm -f $outfile
+}
+          
+# This is same as TOOLTESTV() with comparing h5dump output
+# from -pH option
+#
+TOOLTEST_DUMP() 
+{
+    infile=$TESTDIR/$2
+    outfile=$TESTDIR/out-$1.$2
+    expect="$TESTDIR/$1.$2.ddl"
+    actual="$TESTDIR/out-$1.$2.out"
+    actual_err="$TESTDIR/out-$1.$2.err"
+
+    shift
+    shift
+    
+    # Run test.
+    TESTING $H5REPACK $@
+    (
+        $RUNSERIAL $H5REPACK_BIN "$@" $infile $outfile
+    ) >$actual 2>$actual_err
+    RET=$?
+    if [ $RET != 0 ] ; then
+    echo "*FAILED*"
+    nerrors="`expr $nerrors + 1`"
+    else
+     echo " PASSED"
+     VERIFY h5dump output $@
+     (
+        $RUNSERIAL $H5DUMP_BIN -pH $outfile 
+     ) >$actual 2>$actual_err
+     cat $actual_err >> $actual
+
+     RET=$?
+          
+    fi
+
     if cmp -s $expect $actual; then
      echo " PASSED"
     else
@@ -543,6 +610,40 @@ TOOLTEST_META()
     
     rm -f $outfile
 }
+# ADD_HELP_TEST
+TOOLTEST_HELP() {
+
+    expect="$TESTDIR/$1"
+    actual="$TESTDIR/`basename $1 .txt`.out"
+    actual_err="$TESTDIR/`basename $1 .txt`.err"
+    shift
+
+    # Run test.
+    TESTING $H5REPACK $@
+    (
+      cd $TESTDIR
+      $RUNSERIAL $H5REPACK_BIN "$@"
+    ) >$actual 2>$actual_err
+    cat $actual_err >> $actual
+
+    if [ ! -f $expect ]; then
+    # Create the expect data file if it doesn't yet exist.
+      echo " CREATED"
+      cp $actual $expect-CREATED
+    elif cmp -s $expect $actual; then
+      echo " PASSED"
+    else
+      echo "*FAILED*"
+      echo "    Expected output (*.txt) differs from actual output (*.out)"
+      nerrors="`expr $nerrors + 1`"
+    fi
+    
+    # Clean up output file
+    if test -z "$HDF5_NOCLEANUP"; then
+     rm -f $actual $actual_err
+    fi
+
+}
 
 # This is different from $srcdir/../../bin/output_filter.sh
 STDOUT_FILTER() {
@@ -580,6 +681,8 @@ fi
 ##############################################################################
 # prepare for test
 COPY_TESTFILES_TO_TESTDIR
+
+TOOLTEST_HELP h5repack-help.txt -h
 
 # copy files (these files have no filters) 
 TOOLTEST fill h5repack_fill.h5
@@ -820,7 +923,7 @@ arg="h5repack_layout.h5 -f GZIP=1 -m 1024"
 if test $USE_FILTER_DEFLATE != "yes"  ; then
  SKIP $arg
 else
- TOOLTEST deflate_limit $arg
+ TOOLTEST_DUMP deflate_limit $arg
 fi
 
 #file
@@ -998,6 +1101,9 @@ TOOLTEST HDFFV-7840 h5diff_attr1.h5
 # tests for metadata block size option 
 TOOLTEST_META meta_short h5repack_layout.h5 -M 8192
 TOOLTEST_META meta_long h5repack_layout.h5 --metadata_block_size=8192
+
+# Clean up temporary files/directories
+CLEAN_TESTFILES_AND_TESTDIR
 
 if test $nerrors -eq 0 ; then
     echo "All $TESTNAME tests passed."
