hdf5-1.8.8

diff --git a/tools/h5ls/testh5ls.sh.in b/tools/h5ls/testh5ls.sh.in
--- a/tools/h5ls/testh5ls.sh.in
+++ b/tools/h5ls/testh5ls.sh.in
@@ -24,6 +24,7 @@ H5LS_BIN=`pwd`/$H5LS    # The path of the tool binary
 
 CMP='cmp -s'
 DIFF='diff -c'
+CP='cp'
 NLINES=20			# Max. lines of output to display if test fails
 
 WORDS_BIGENDIAN="@WORDS_BIGENDIAN@"
@@ -31,12 +32,115 @@ WORDS_BIGENDIAN="@WORDS_BIGENDIAN@"
 nerrors=0
 verbose=yes
 h5haveexitcode=yes	    # default is yes
-
 # The build (current) directory might be different than the source directory.
 if test -z "$srcdir"; then
     srcdir=.
 fi
-test -d ../testfiles || mkdir ../testfiles
+# source dirs
+SRC_TOOLS="$srcdir/.."
+SRC_TOOLS_TESTFILES="$SRC_TOOLS/testfiles"
+# testfiles source dirs for tools
+SRC_H5LS_TESTFILES="$SRC_TOOLS_TESTFILES"
+SRC_H5DUMP_TESTFILES="$SRC_TOOLS_TESTFILES"
+SRC_H5DIFF_TESTFILES="$SRC_TOOLS/h5diff/testfiles"
+SRC_H5COPY_TESTFILES="$SRC_TOOLS/h5copy/testfiles"
+SRC_H5REPACK_TESTFILES="$SRC_TOOLS/h5repack/testfiles"
+SRC_H5JAM_TESTFILES="$SRC_TOOLS/h5jam/testfiles"
+SRC_H5STAT_TESTFILES="$SRC_TOOLS/h5stat/testfiles"
+SRC_H5IMPORT_TESTFILES="$SRC_TOOLS/h5import/testfiles"
+
+TESTDIR=./testfiles
+test -d $TESTDIR || mkdir $TESTDIR
+
+######################################################################
+# test files
+# --------------------------------------------------------------------
+# All the test files copy from source directory to test directory
+# NOTE: Keep this framework to add/remove test files.
+#       Any test files from other tools can be used in this framework.
+#       This list are also used for checking exist.
+#       Comment '#' without space can be used.
+# --------------------------------------------------------------------
+LIST_HDF5_TEST_FILES="
+$SRC_H5LS_TESTFILES/tall.h5
+$SRC_H5LS_TESTFILES/tarray1.h5
+$SRC_H5LS_TESTFILES/tattr2.h5
+$SRC_H5LS_TESTFILES/tcompound.h5
+$SRC_H5LS_TESTFILES/tdatareg.h5
+$SRC_H5LS_TESTFILES/tdset.h5
+$SRC_H5LS_TESTFILES/tempty.h5
+$SRC_H5LS_TESTFILES/textlink.h5
+$SRC_H5LS_TESTFILES/textlinksrc.h5
+$SRC_H5LS_TESTFILES/textlinktar.h5
+$SRC_H5LS_TESTFILES/tgroup.h5
+$SRC_H5LS_TESTFILES/tgrp_comments.h5
+$SRC_H5LS_TESTFILES/thlink.h5
+$SRC_H5LS_TESTFILES/tloop.h5
+$SRC_H5LS_TESTFILES/tnestedcomp.h5
+$SRC_H5LS_TESTFILES/tsaf.h5
+$SRC_H5LS_TESTFILES/tslink.h5
+$SRC_H5LS_TESTFILES/tsoftlinks.h5
+$SRC_H5LS_TESTFILES/tstr.h5
+$SRC_H5LS_TESTFILES/tudlink.h5
+$SRC_H5LS_TESTFILES/tvldtypes1.h5
+"
+
+LIST_OTHER_TEST_FILES="
+$SRC_H5LS_TESTFILES/help-1.ls
+$SRC_H5LS_TESTFILES/help-2.ls
+$SRC_H5LS_TESTFILES/help-3.ls
+$SRC_H5LS_TESTFILES/nosuchfile.ls
+$SRC_H5LS_TESTFILES/tall-1.ls
+$SRC_H5LS_TESTFILES/tall-2.ls
+$SRC_H5LS_TESTFILES/tarray1.ls
+$SRC_H5LS_TESTFILES/tattr2.ls
+$SRC_H5LS_TESTFILES/tcomp-1.ls
+$SRC_H5LS_TESTFILES/tdataregbe.ls
+$SRC_H5LS_TESTFILES/tdataregle.ls
+$SRC_H5LS_TESTFILES/tdset-1.ls
+$SRC_H5LS_TESTFILES/tempty.ls
+$SRC_H5LS_TESTFILES/textlink-1.ls
+$SRC_H5LS_TESTFILES/textlinksrc-1.ls
+$SRC_H5LS_TESTFILES/textlinksrc-2.ls
+$SRC_H5LS_TESTFILES/textlinksrc-3.ls
+$SRC_H5LS_TESTFILES/textlinksrc-4.ls
+$SRC_H5LS_TESTFILES/textlinksrc-5.ls
+$SRC_H5LS_TESTFILES/textlinksrc-6.ls
+$SRC_H5LS_TESTFILES/textlinksrc-7.ls
+$SRC_H5LS_TESTFILES/textlinksrc-1-old.ls
+$SRC_H5LS_TESTFILES/textlinksrc-2-old.ls
+$SRC_H5LS_TESTFILES/textlinksrc-3-old.ls
+$SRC_H5LS_TESTFILES/textlinksrc-6-old.ls
+$SRC_H5LS_TESTFILES/textlinksrc-7-old.ls
+$SRC_H5LS_TESTFILES/tsoftlinks-1.ls
+$SRC_H5LS_TESTFILES/tsoftlinks-2.ls
+$SRC_H5LS_TESTFILES/tsoftlinks-3.ls
+$SRC_H5LS_TESTFILES/tsoftlinks-4.ls
+$SRC_H5LS_TESTFILES/tsoftlinks-5.ls
+$SRC_H5LS_TESTFILES/textlinksrc-nodangle-1.ls
+$SRC_H5LS_TESTFILES/textlinksrc-nodangle-2.ls
+$SRC_H5LS_TESTFILES/tgrp_comments.ls
+$SRC_H5LS_TESTFILES/tsoftlinks-nodangle-1.ls
+$SRC_H5LS_TESTFILES/thlinks-nodangle-1.ls
+$SRC_H5LS_TESTFILES/tgroup.ls
+$SRC_H5LS_TESTFILES/tgroup-1.ls
+$SRC_H5LS_TESTFILES/tgroup-2.ls
+$SRC_H5LS_TESTFILES/tgroup-3.ls
+$SRC_H5LS_TESTFILES/thlink-1.ls
+$SRC_H5LS_TESTFILES/tloop-1.ls
+$SRC_H5LS_TESTFILES/tnestcomp-1.ls
+$SRC_H5LS_TESTFILES/tnestcomp-2.ls
+$SRC_H5LS_TESTFILES/tnestcomp-3.ls
+$SRC_H5LS_TESTFILES/tnestcomp-4.ls
+$SRC_H5LS_TESTFILES/tsaf.ls
+$SRC_H5LS_TESTFILES/tslink-1.ls
+$SRC_H5LS_TESTFILES/tstr-1.ls
+$SRC_H5LS_TESTFILES/tudlink-1.ls
+$SRC_H5LS_TESTFILES/tvldtypes1.ls
+$SRC_H5LS_TESTFILES/tvldtypes2le.ls
+$SRC_H5LS_TESTFILES/tvldtypes2be.ls
+"
+
 
 # RUNSERIAL is used. Check if it can return exit code from executalbe correctly.
 if [ -n "$RUNSERIAL_NOEXITCODE" ]; then
@@ -45,6 +149,31 @@ if [ -n "$RUNSERIAL_NOEXITCODE" ]; then
     h5haveexitcode=no
 fi
 
+#
+# copy test files and expected output files from source dirs to test dir
+#
+COPY_TESTFILES="$LIST_HDF5_TEST_FILES $LIST_OTHER_TEST_FILES"
+
+COPY_TESTFILES_TO_TESTDIR()
+{
+    # copy test files. Used -f to make sure get a new copy
+    for tstfile in $COPY_TESTFILES
+    do
+        # ignore '#' comment
+        echo $tstfile | tr -d ' ' | grep '^#' > /dev/null
+        RET=$?
+        if [ $RET -eq 1 ]; then
+            if [ -a $tstfile ]; then
+                $CP -f $tstfile $TESTDIR
+            else
+                echo "Error: FAILED to copy $tstfile"
+                echo "       $tstfile doesn't exist!"
+                exit $EXIT_FAILURE
+            fi
+        fi
+    done
+}
+
 # Print a line-line message left justified in a field of 70 characters
 # beginning with the word "Testing".
 TESTING() {
@@ -52,89 +181,8 @@ TESTING() {
     echo "Testing $* $SPACES" |cut -c1-70 |tr -d '\012'
 }
 
-# Some systems will dump some messages to stdout for various reasons.
-# Remove them from the stdout result file.
-# $1 is the file name of the file to be filtered.
-# Cases of filter needed:
-# 1. Sandia Red-Storm
-#    yod always prints these two lines at the beginning.
-#    LibLustre: NAL NID: 0004a605 (5)
-#    Lustre: OBD class driver Build Version: 1, info@clusterfs.com
-# 2. LANL Lambda
-#    mpijob mirun -np always add an extra line at the end like:
-#    P4 procgroup file is /users/acheng/.lsbatch/host10524.l82
-STDOUT_FILTER() {
-    result_file=$1
-    tmp_file=/tmp/h5test_tmp_$$
-    # Filter Sandia Red-Storm yod messages.
-    cp $result_file $tmp_file
-    sed -e '/^LibLustre:/d' -e '/^Lustre:/d' \
-	< $tmp_file > $result_file
-    # Filter LANL Lambda mpirun message.
-    cp $result_file $tmp_file
-    sed -e '/^P4 procgroup file is/d' \
-	< $tmp_file > $result_file
-    # cleanup
-    rm -f $tmp_file
-}
-
-# Some systems will dump some messages to stderr for various reasons.
-# Remove them from the stderr result file.
-# $1 is the file name of the file to be filtered.
-# Cases of filter needed:
-# 1. MPE:
-# In parallel mode and if MPE library is used, it prints the following
-# two message lines whether the MPE tracing is used or not.
-#    Writing logfile.
-#    Finished writing logfile.
-# 2. LANL MPI:
-# The LANL MPI will print some messages like the following,
-#    LA-MPI: *** mpirun (1.5.10)
-#    LA-MPI: *** 3 process(es) on 2 host(s): 2*fln21 1*fln22
-#    LA-MPI: *** libmpi (1.5.10)
-#    LA-MPI: *** Copyright 2001-2004, ACL, Los Alamos National Laboratory
-# 3. h5diff debug output:
-#    Debug output all have prefix "h5diff debug: ".
-# 4. AIX system prints messages like these when it is aborting:
-#    ERROR: 0031-300  Forcing all remote tasks to exit due to exit code 1 in task 0
-#    ERROR: 0031-250  task 4: Terminated
-#    ERROR: 0031-250  task 3: Terminated
-#    ERROR: 0031-250  task 2: Terminated
-#    ERROR: 0031-250  task 1: Terminated
-# 5. LLNL Blue-Gene mpirun prints messages like there when it exit non-zero:
-#    <Apr 12 15:01:49.075658> BE_MPI (ERROR): The error message in the job record is as follows:
-#    <Apr 12 15:01:49.075736> BE_MPI (ERROR):   "killed by exit(1) on node 0"
-
-
-STDERR_FILTER() {
-    result_file=$1
-    tmp_file=/tmp/h5test_tmp_$$
-    # Filter LLNL Blue-Gene error messages in both serial and parallel modes
-    # since mpirun is used in both modes.
-    cp $result_file $tmp_file
-    sed -e '/ BE_MPI (ERROR): /d' \
-	< $tmp_file > $result_file
-    # Filter MPE messages
-    if test -n "$pmode"; then
-	cp $result_file $tmp_file
-	sed -e '/^Writing logfile./d' -e '/^Finished writing logfile./d' \
-	    < $tmp_file > $result_file
-    fi
-    # Filter LANL MPI messages
-    # and LLNL srun messages
-    # and AIX error messages
-    if test -n "$pmode"; then
-	cp $result_file $tmp_file
-	sed -e '/^LA-MPI:/d' -e '/^srun:/d' -e '/^ERROR:/d' \
-	    < $tmp_file > $result_file
-    fi
-    # Filter h5diff debug output
-	cp $result_file $tmp_file
-	sed -e '/^h5diff debug: /d' \
-	    < $tmp_file > $result_file
-    # clean up temporary files.
-    rm -f $tmp_file
-}
+# Source in the output filter function definitions.
+. $srcdir/../../bin/output_filter.sh
 
 # Run a test and print PASS or *FAIL*. For now, if h5ls can complete
 # with exit status 0, consider it pass. If a test fails then increment
@@ -145,9 +193,9 @@ STDERR_FILTER() {
 # $1 -- actual output filename to use
 # $2 and on -- argument for the h5ls tool
 TOOLTEST() {
-    expect="$srcdir/../testfiles/$1"
-    actual="../testfiles/`basename $1 .ls`.out"
-    actual_err="../testfiles/`basename $1 .ls`.err"
+    expect="$TESTDIR/$1"
+    actual="$TESTDIR/`basename $1 .ls`.out"
+    actual_err="$TESTDIR/`basename $1 .ls`.err"
     actual_sav=${actual}-sav
     actual_err_sav=${actual_err}-sav
     shift
@@ -159,10 +207,7 @@ TOOLTEST() {
     # any unexpected output from that stream too.
     TESTING $H5LS $@
     (
-	echo "#############################"
-	echo " output for '$H5LS $@'" 
-	echo "#############################"
-	cd $srcdir/../testfiles
+	cd $TESTDIR
         $RUNSERIAL $H5LS_BIN "$@"
     ) >$actual 2>$actual_err 
     
@@ -207,6 +252,8 @@ TOOLTEST() {
 ###			  T H E   T E S T S                                ###
 ##############################################################################
 ##############################################################################
+# prepare for test
+COPY_TESTFILES_TO_TESTDIR
 
 # Toss in a bunch of tests.  Not sure if they are the right kinds.
 # test the help syntax
