hdf5-1.8.5

diff --git a/tools/h5dump/testh5dump.sh.in b/tools/h5dump/testh5dump.sh.in
--- a/tools/h5dump/testh5dump.sh.in
+++ b/tools/h5dump/testh5dump.sh.in
@@ -23,6 +23,13 @@ USE_FILTER_FLETCHER32="@USE_FILTER_FLETCHER32@"
 USE_FILTER_NBIT="@USE_FILTER_NBIT@"
 USE_FILTER_SCALEOFFSET="@USE_FILTER_SCALEOFFSET@"
 
+# Determine if H5dump packed bits feature is included
+Have_Packed_Bits="@PACKED_BITS@"
+
+TESTNAME=h5dump
+EXIT_SUCCESS=0
+EXIT_FAILURE=1
+
 DUMPER=h5dump                     # The tool name
 DUMPER_BIN=`pwd`/$DUMPER          # The path of the tool binary
 TESTDIR=`pwd`/../testfiles
@@ -325,7 +332,11 @@ TOOLTEST tchar1.ddl -r tchar.h5
 
 # test failure handling
 # Missing file name
-TOOLTEST tnofilename.ddl
+if test "$Have_Packed_Bits" = "yes"; then
+    TOOLTEST tnofilename-with-packed-bits.ddl
+else
+    TOOLTEST tnofilename.ddl
+fi
 
 # rev. 2004
 
@@ -477,8 +488,6 @@ if test -z "$HDF5_NOCLEANUP"; then
  rm -f $TESTDIR/out3.h5
 fi
 
-
-
 # test for dataset region references 
 TOOLTEST tdatareg.ddl tdatareg.h5
 TOOLTEST tdataregR.ddl -R tdatareg.h5
@@ -499,7 +508,6 @@ TOOLTEST torderattr2.ddl -H --sort_by=name --sort_order=descending torderattr.h5
 TOOLTEST torderattr3.ddl -H --sort_by=creation_order --sort_order=ascending torderattr.h5
 TOOLTEST torderattr4.ddl -H --sort_by=creation_order --sort_order=descending torderattr.h5
 
-
 # tests for floating point user defined printf format
 TOOLTEST tfpformat.ddl -m %.7f tfpformat.h5
 
@@ -507,12 +515,51 @@ TOOLTEST tfpformat.ddl -m %.7f tfpformat.h5
 TOOLTEST textlinksrc.ddl textlinksrc.h5
 TOOLTEST textlinkfar.ddl textlinkfar.h5
 
-
-
-
-if test $nerrors -eq 0 ; then
-   echo "All $DUMPER tests passed."
+# test for dataset packed bits 
+# Set up xCMD to test or skip.
+if test "$Have_Packed_Bits" = "yes"; then
+    xCMD=TOOLTEST
+else
+    xCMD=SKIP
 fi
+# Limits:
+# Maximum number of packed bits is 8 (for now).
+# Maximum integer size is 8 (for now).
+# Maximun Offset is 7 (Maximum size - 1).
+# Maximum Offset+Length is 8 (Maximum size).
+# Tests:
+# Normal operation on both signed and unsigned int datasets.
+# Their rawdata output should be the same.
+$xCMD tpbitsSigned.ddl -d /DS08BITS -M 0,2,2,6 packedbits.h5
+$xCMD tpbitsUnsigned.ddl -d /DU08BITS -M 0,2,2,6 packedbits.h5
+# Overlapped packed bits.
+$xCMD tpbitsOverlapped.ddl -d /DS08BITS -M 0,1,1,1,2,1,0,3 packedbits.h5
+# Maximum number of packed bits.
+$xCMD tpbitsMax.ddl -d /DS08BITS -M 0,1,1,1,2,1,3,1,4,1,5,1,6,1,7,1 packedbits.h5
+# Compound type.
+$xCMD tpbitsCompound.ddl -d /dset1 -M 0,1,1,1 tcompound.h5
+# Array type.
+$xCMD tpbitsArray.ddl -d /Dataset1 -M 0,1,1,1 tarray1.h5
+# Test Error handling.
+# Too many packed bits requested. Max is 8 for now.
+$xCMD tpbitsMaxExceeded.ddl -d /DS08BITS -M 0,1,0,1,1,1,2,1,3,1,4,1,5,1,6,1,7,1 packedbits.h5
+# Offset too large. Max is 7 (8-1) for now.
+$xCMD tpbitsOffsetExceeded.ddl -d /DS08BITS -M 8,1 packedbits.h5
+# Bad offset, must not be negative.
+$xCMD tpbitsOffsetNegative.ddl -d /DS08BITS -M -1,1 packedbits.h5
+# Bad length, must not be positive.
+$xCMD tpbitsLengthPositive.ddl -d /DS08BITS -M 4,0 packedbits.h5
+# Offset+Length is too large. Max is 8 for now.
+$xCMD tpbitsLengthExceeded.ddl -d /DS08BITS -M 2,7 packedbits.h5
+# Incomplete pair of packed bits request.
+$xCMD tpbitsIncomplete.ddl -d /DS08BITS -M 0,2,2,1,0,2,2, packedbits.h5
 
-exit $nerrors
 
+# Report test results and exit
+if test $nerrors -eq 0 ; then
+    echo "All $TESTNAME tests passed."
+    exit $EXIT_SUCCESS
+else
+    echo "$TESTNAME tests failed with $nerrors errors."
+    exit $EXIT_FAILURE
+fi
diff --git a/tools/h5repack/h5repack.sh.in b/tools/h5repack/h5repack.sh.in
--- a/tools/h5repack/h5repack.sh.in
+++ b/tools/h5repack/h5repack.sh.in
@@ -27,6 +27,10 @@ USE_FILTER_FLETCHER32="@USE_FILTER_FLETCHER32@"
 USE_FILTER_NBIT="@USE_FILTER_NBIT@"
 USE_FILTER_SCALEOFFSET="@USE_FILTER_SCALEOFFSET@"
 
+TESTNAME=h5repack
+EXIT_SUCCESS=0
+EXIT_FAILURE=1
+
 H5REPACK=h5repack               # The tool name
 H5REPACK_BIN=`pwd`/$H5REPACK    # The path of the tool binary
 
@@ -55,6 +59,7 @@ FILE14=h5repack_layouto.h5      # A file with an older version of the layout mes
                                 # (copy of test/tlayouto.h5)
 FILE15=h5repack_named_dtypes.h5
 FILE16=tfamily%05d.h5           # located in common testfiles folder
+FILE_REF=h5repack_refs.h5
 
 
 nerrors=0
@@ -527,9 +532,14 @@ TOOLTEST $FILE15
 # tests family driver (file is located in common testfiles folder, uses TOOLTEST1
 TOOLTEST1 $FILE16
 
-if test $nerrors -eq 0 ; then
-   echo "All $H5REPACK tests passed."
-fi
+# test various references (bug 1814 and 1726)
+TOOLTEST $FILE_REF
 
-exit $nerrors
+if test $nerrors -eq 0 ; then
+    echo "All $TESTNAME tests passed."
+    exit $EXIT_SUCCESS
+else
+    echo "$TESTNAME tests failed with $nerrors errors."
+    exit $EXIT_FAILURE
+fi
 
diff --git a/tools/h5stat/testh5stat.sh.in b/tools/h5stat/testh5stat.sh.in
--- a/tools/h5stat/testh5stat.sh.in
+++ b/tools/h5stat/testh5stat.sh.in
@@ -23,6 +23,10 @@ USE_FILTER_FLETCHER32="@USE_FILTER_FLETCHER32@"
 USE_FILTER_NBIT="@USE_FILTER_NBIT@"
 USE_FILTER_SCALEOFFSET="@USE_FILTER_SCALEOFFSET@"
 
+TESTNAME=h5stat
+EXIT_SUCCESS=0
+EXIT_FAILURE=1
+
 STAT=h5stat               # The tool name
 STAT_BIN=`pwd`/$STAT    # The path of the tool binary
 
@@ -119,17 +123,22 @@ TOOLTEST h5stat_filters-F.ddl  -F   h5stat_filters.h5
 TOOLTEST h5stat_filters-d.ddl  -d   h5stat_filters.h5
 TOOLTEST h5stat_filters-g.ddl  -g   h5stat_filters.h5
 TOOLTEST h5stat_filters-dT.ddl -dT  h5stat_filters.h5
+TOOLTEST h5stat_filters-UD.ddl -D h5stat_filters.h5
+TOOLTEST h5stat_filters-UT.ddl -T h5stat_filters.h5
 # h5stat_tsohm.h5 is a copy of ../../../test/tsohm.h5 generated by tsohm.c 
 # as of release 1.8.0-alpha4
 TOOLTEST h5stat_tsohm.ddl h5stat_tsohm.h5
 # h5stat_newgrat.h5 is generated by h5stat_gentest.c
 TOOLTEST h5stat_newgrat.ddl h5stat_newgrat.h5
-echo
+TOOLTEST h5stat_newgrat-UG.ddl -G h5stat_newgrat.h5
+TOOLTEST h5stat_newgrat-UA.ddl -A h5stat_newgrat.h5
 
 
 if test $nerrors -eq 0 ; then
-   echo "All $STAT tests passed."
+    echo "All $TESTNAME tests passed."
+    exit $EXIT_SUCCESS
+else
+    echo "$TESTNAME tests failed with $nerrors errors."
+    exit $EXIT_FAILURE
 fi
-
-exit $nerrors
 
